/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    authors: Author;
    categories: Category;
    tags: Tag;
    posts: Post;
    redirects: Redirect;
    leads: Lead;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  fullName: string;
  roles: ('admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Bắt buộc — dùng cho accessibility và SEO ảnh.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * Bỏ trống để tự tạo từ tên.
   */
  slug?: string | null;
  /**
   * VD: Số CCCH LS xxx/ĐLN — tín hiệu E-E-A-T cho schema Person
   */
  credentials?: string | null;
  bio?: string | null;
  photo?: (number | null) | Media;
  /**
   * URL profile, cách nhau bằng dấu phẩy
   */
  sameAs?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Cách DUY NHẤT để một trang mang noindex. Không bật nếu không chắc chắn (spec §6.5).
     */
    noindex?: boolean | null;
    canonicalOverride?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  title: string;
  slug?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Cách DUY NHẤT để một trang mang noindex. Không bật nếu không chắc chắn (spec §6.5).
     */
    noindex?: boolean | null;
    canonicalOverride?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Bỏ trống để tự tạo từ tiêu đề.
   */
  slug?: string | null;
  /**
   * Trang có đúng MỘT thẻ H1 lấy từ trường này (spec §6.4).
   */
  primaryHeading: string;
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  categories?: (number | Category)[] | null;
  tags?: (number | Tag)[] | null;
  author: number | Author;
  publishedAt: string;
  featured?: boolean | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Cách DUY NHẤT để một trang mang noindex. Không bật nếu không chắc chắn (spec §6.5).
     */
    noindex?: boolean | null;
    canonicalOverride?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  /**
   * Bỏ trống nếu chọn 410
   */
  to?: string | null;
  type: '301' | '302' | '410';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email?: string | null;
  phone?: string | null;
  subject?: string | null;
  message?: string | null;
  attribution?: {
    sourcePage?: string | null;
    sourceUrl?: string | null;
    referrer?: string | null;
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
  };
  compliance: {
    consentedAt: string;
    consentVersion: string;
    /**
     * Không lưu IP thô
     */
    ipHash?: string | null;
  };
  status?: ('new' | 'contacted' | 'closed') | null;
  internalNotes?: string | null;
  submittedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Giữ nguyên slug cũ khi chuyển nội dung — URL đang dùng không được đổi (spec §6.7).
   */
  slug: string;
  /**
   * Trang có đúng MỘT thẻ H1 lấy từ trường này. Trang chủ PHẢI chứa chuỗi "Luật Gia Trí" (spec §6.9).
   */
  primaryHeading: string;
  layout: (
    | {
        image: number | Media;
        headline: string;
        subheadline?: string | null;
        ctaLabel?: string | null;
        ctaHref?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        slides: {
          image: number | Media;
          headline: string;
          subheadline?: string | null;
          ctaLabel?: string | null;
          ctaHref?: string | null;
          id?: string | null;
        }[];
        intervalMs?: number | null;
        /**
         * Banner cũ trên site đã chứa sẵn chữ trong ảnh — để tắt (mặc định) cho các banner đó, tránh chữ chồng chữ. Bật khi ảnh là ảnh nền trơn và cần phủ tiêu đề.
         */
        showOverlay?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'heroCarousel';
      }
    | {
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        image: number | Media;
        heading: string;
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        bullets?:
          | {
              item: string;
              id?: string | null;
            }[]
          | null;
        reverse?: boolean | null;
        ctaLabel?: string | null;
        ctaHref?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'servicePair';
      }
    | {
        heading?: string | null;
        items: {
          title: string;
          body: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'featureGrid';
      }
    | {
        heading: string;
        /**
         * service-term-fee dùng cho ma trận chữ ký số (spec §5.5)
         */
        columns: 'service-fee' | 'service-term-fee';
        groups?:
          | {
              title?: string | null;
              rows: {
                service: string;
                term?: string | null;
                fee: string;
                id?: string | null;
              }[];
              id?: string | null;
            }[]
          | null;
        note?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'pricingTable';
      }
    | {
        heading: string;
        sections: {
          title: string;
          columns: {
            label: string;
            id?: string | null;
          }[];
          rows: {
            cells: {
              value: string;
              id?: string | null;
            }[];
            id?: string | null;
          }[];
          id?: string | null;
        }[];
        note?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'tokenMatrix';
      }
    | {
        heading?: string | null;
        items: {
          question: string;
          answer: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'faq';
      }
    | {
        heading?: string | null;
        items: {
          quote: string;
          name: string;
          role?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'testimonials';
      }
    | {
        logos: {
          image: number | Media;
          url?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'customerLogoStrip';
      }
    | {
        heading?: string | null;
        members: (number | Author)[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'teamGrid';
      }
    | {
        heading?: string | null;
        steps: {
          title: string;
          body: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'processSteps';
      }
    | {
        eyebrow?: string | null;
        heading: string;
        body?: string | null;
        ctaLabel?: string | null;
        ctaHref?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ctaBanner';
      }
    | {
        heading?: string | null;
        ctaHref?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'newsPreview';
      }
  )[];
  serviceMeta?: {
    serviceName?: string | null;
    shortDescription?: string | null;
    fromPrice?: string | null;
    icon?: (number | null) | Media;
    relatedServices?: (number | Page)[] | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Cách DUY NHẤT để một trang mang noindex. Không bật nếu không chắc chắn (spec §6.5).
     */
    noindex?: boolean | null;
    canonicalOverride?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullName?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  credentials?: T;
  bio?: T;
  photo?: T;
  sameAs?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        noindex?: T;
        canonicalOverride?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        noindex?: T;
        canonicalOverride?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  primaryHeading?: T;
  excerpt?: T;
  heroImage?: T;
  body?: T;
  categories?: T;
  tags?: T;
  author?: T;
  publishedAt?: T;
  featured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        noindex?: T;
        canonicalOverride?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  attribution?:
    | T
    | {
        sourcePage?: T;
        sourceUrl?: T;
        referrer?: T;
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
      };
  compliance?:
    | T
    | {
        consentedAt?: T;
        consentVersion?: T;
        ipHash?: T;
      };
  status?: T;
  internalNotes?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  primaryHeading?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              image?: T;
              headline?: T;
              subheadline?: T;
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        heroCarousel?:
          | T
          | {
              slides?:
                | T
                | {
                    image?: T;
                    headline?: T;
                    subheadline?: T;
                    ctaLabel?: T;
                    ctaHref?: T;
                    id?: T;
                  };
              intervalMs?: T;
              showOverlay?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              body?: T;
              id?: T;
              blockName?: T;
            };
        servicePair?:
          | T
          | {
              image?: T;
              heading?: T;
              body?: T;
              bullets?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              reverse?: T;
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pricingTable?:
          | T
          | {
              heading?: T;
              columns?: T;
              groups?:
                | T
                | {
                    title?: T;
                    rows?:
                      | T
                      | {
                          service?: T;
                          term?: T;
                          fee?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              note?: T;
              id?: T;
              blockName?: T;
            };
        tokenMatrix?:
          | T
          | {
              heading?: T;
              sections?:
                | T
                | {
                    title?: T;
                    columns?:
                      | T
                      | {
                          label?: T;
                          id?: T;
                        };
                    rows?:
                      | T
                      | {
                          cells?:
                            | T
                            | {
                                value?: T;
                                id?: T;
                              };
                          id?: T;
                        };
                    id?: T;
                  };
              note?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    quote?: T;
                    name?: T;
                    role?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        customerLogoStrip?:
          | T
          | {
              logos?:
                | T
                | {
                    image?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        teamGrid?:
          | T
          | {
              heading?: T;
              members?: T;
              id?: T;
              blockName?: T;
            };
        processSteps?:
          | T
          | {
              heading?: T;
              steps?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBanner?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        newsPreview?:
          | T
          | {
              heading?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
      };
  serviceMeta?:
    | T
    | {
        serviceName?: T;
        shortDescription?: T;
        fromPrice?: T;
        icon?: T;
        relatedServices?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        noindex?: T;
        canonicalOverride?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Nguồn gốc duy nhất cho tiêu đề, og:site_name và schema. Không dùng "MẠCH GIA PHÁT" (lỗi của site cũ).
   */
  brandName: string;
  legalEntityName?: string | null;
  taxCode?: string | null;
  hotline: string;
  email: string;
  address: {
    street: string;
    ward?: string | null;
    district: string;
    city: string;
    country: string;
  };
  /**
   * Ví dụ: Mo-Fr 08:00-17:30
   */
  openingHours?: string | null;
  socials?: {
    facebook?: string | null;
    zalo?: string | null;
    youtube?: string | null;
    googleBusinessProfile?: string | null;
  };
  defaultOgImage?: (number | null) | Media;
  /**
   * Để trống nếu chưa dùng
   */
  ga4Id?: string | null;
  gscVerificationToken?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  headerItems: {
    label: string;
    href: string;
    id?: string | null;
  }[];
  footerLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  legalEntityName?: T;
  taxCode?: T;
  hotline?: T;
  email?: T;
  address?:
    | T
    | {
        street?: T;
        ward?: T;
        district?: T;
        city?: T;
        country?: T;
      };
  openingHours?: T;
  socials?:
    | T
    | {
        facebook?: T;
        zalo?: T;
        youtube?: T;
        googleBusinessProfile?: T;
      };
  defaultOgImage?: T;
  ga4Id?: T;
  gscVerificationToken?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  headerItems?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}